#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login shell has a defined environment.
if [[ ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Custom envs
#

export PATH="$PATH:/usr/local/opt/fzf/bin:$HOME/.fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# custom bin dir
export PATH="$PATH:$HOME/.config/bin:$HOME/.config/yabai/bin"

# custom shell commands
# chmod +x $ZDOTDIR/bin/*
export PATH="$ZDOTDIR/bin:$PATH"

#
# Gcloud
#
export PATH="$PATH:$HOME/google-cloud-sdk/bin"

#
# Krew (kubernetes plugin manager)
#
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

. "$HOME/.cargo/env"
